// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPypdLNhOUMis9Cg-kkJPcv5zclNIx6ME',
    appId: '1:684687747071:web:f27e872c708150d08229ca',
    messagingSenderId: '684687747071',
    projectId: 'hesapix-6161',
    authDomain: 'hesapix-6161.firebaseapp.com',
    storageBucket: 'hesapix-6161.firebasestorage.app',
    measurementId: 'G-G12Y0Z5L15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-wgpts9Y9Y9jkB32HlzIU8wG52Idpts',
    appId: '1:684687747071:android:13ad8d2398ff984e8229ca',
    messagingSenderId: '684687747071',
    projectId: 'hesapix-6161',
    storageBucket: 'hesapix-6161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSLE_sfwkkS-hyAxOSVEGwplFcyu1OHtw',
    appId: '1:684687747071:ios:a73c93bbfc38a44c8229ca',
    messagingSenderId: '684687747071',
    projectId: 'hesapix-6161',
    storageBucket: 'hesapix-6161.firebasestorage.app',
    iosBundleId: 'com.example.hesapixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSLE_sfwkkS-hyAxOSVEGwplFcyu1OHtw',
    appId: '1:684687747071:ios:a73c93bbfc38a44c8229ca',
    messagingSenderId: '684687747071',
    projectId: 'hesapix-6161',
    storageBucket: 'hesapix-6161.firebasestorage.app',
    iosBundleId: 'com.example.hesapixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPypdLNhOUMis9Cg-kkJPcv5zclNIx6ME',
    appId: '1:684687747071:web:ef706627efac45098229ca',
    messagingSenderId: '684687747071',
    projectId: 'hesapix-6161',
    authDomain: 'hesapix-6161.firebaseapp.com',
    storageBucket: 'hesapix-6161.firebasestorage.app',
    measurementId: 'G-MZEX86HNC9',
  );
}
